version: '3'

networks:
  monreseau:
    external: false

services:
  web:
    build: .
    container_name: monsite_webb1
    volumes:
      - sitestatics:/app/static/                                                                                                                                                                                     
      - sitemedias:/app/medias/  
    depends_on:
      - db
    networks:
      - monreseau

  db:
    image: "postgres:latest"
    container_name: monsite_dbd1
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: docuser
      POSTGRES_PASSWORD: familletoure12
      PGDATA: /data/postgres
    networks:
      - monreseau
    volumes:
      - pgdb:/var/lib/postgresql/data
    

  nginx:
    image: nginx:1.19-alpine
    container_name: monsite_nginxx1
    volumes:
      - sitestatics:/home/app/web/static_assets
      - sitemedias:/home/app/web/medias
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - monreseau
    ports:
      - '86:80'

volumes:
   pgdb:
   sitestatics:
   sitemedias: