# Generated by Django 4.2.5 on 2023-10-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
