# Generated by Django 4.2.5 on 2023-10-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsite', '0002_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
    ]
